### ISSUE TITLE
Generated files included in repository

### ISSUE THREAD

**Issue by realh** [sammydre/ts-for-gjs#17]
The repository includes generated files, such as JS compiled from TS, and the contents of the `out` directory. I've been overlooking them in my PRs and I think having generated files in a git repository should be avoided if possible, and these should be listed in `.gitignore`.

If you want to include these files in the repository to make it more convenient for your own workflow, please could you consider adding a special branch for that?

**Comment by JumpLink** [comment]
@sammydre Can be closed
