### ISSUE TITLE
Is it possible to use ts-for-gjs as dev dependency

### ISSUE THREAD

**Issue by oae** [sammydre/ts-for-gjs#20]
Hi,

I added this as a dev dependency to my project like below;
```
yarn add -D https://github.com/sammydre/ts-for-gjs
```
After that when I try to run `yarn run ts-for-gir generate` I am getting the following error;
```sh
$ /home/alperen/code/extensions-sync-x/node_modules/.bin/ts-for-gir generate
 ›   Error: command generate not found
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
As I checked `node_modules/.bin/ts-for-gir` in my project is symlinked to `node_modules/ts-for-gir/bin/run`. It seems correct but it cannot find the commands.

If i checkout this repository and link it, then it works. Any idea on this?

Thanks for this great project :fire: :fire:

**Comment by oae** [comment]
It seems like generated `lib` directory is not in the repository so that is why it cannot find the commands.

**Comment by JumpLink** [comment]
Oh yes you are right, even if this is a problem lib should not be included in the repo. It would be better if this project is published at npm. I will discuss this with @sammydre

**Comment by oae** [comment]
Hi again. I still cannot use it as dev dependency using github URL. Should I wait for npm release?
