### ISSUE TITLE
No definitions for node-gtk

### ISSUE THREAD

**Issue by manen** [sammydre/ts-for-gjs#26]
Hi! I'm having an issue with ts-for-gjs.

I need typings for a small project made with node-gtk, but when I try to run `ts-for-gir generate '*' -e node`, it says done, but then I don't have any IntelliSense in Visual Studio Code.

When I require node-gtk, i have IntelliSense on that, but when i do `gi.require("Gtk", "3.0")`, it doesn't provide any IntelliSense.

OS: Fedora 32
NodeJS version: v12.18.2
ts-for-gjs version: 1.0.0
ts-for-gjs commit: 8ee01732c33ac659a41da48838f76b633318d708

**Comment by JumpLink** [comment]
What's the output of `ls /usr/share/gir-1.0` and what's the os you are running?

You need to have the *.gir files you want to generate typescript definition files for. By default ts-for-gir is looking in `/usr/share/gir-1.0` for but you can also change the path with `-g`: `ts-for-gir generate '*' -e node -g /path/to/your/gir-files`.

The [here](https://github.com/sammydre/ts-for-gjs#development) to see how you can install the gir files on ubuntu.

**Comment by JumpLink** [comment]
@manen

**Comment by JumpLink** [comment]
The repository has changed a lot since this issue, so I assume that this issue will no longer fit the current code.

**Comment by manen** [comment]
yeah.. you're probably right
sorry for ghosting you for like 2 straight years by the way
