### ISSUE TITLE
[gjsify] False positives in check for circular dependencies

### ISSUE THREAD

**Issue by realh** [sammydre/ts-for-gjs#28]
@JumpLink: I think you're maintaining the gjsify fork? In that fork I've found a problem in `GirModule.traverseInheritanceTree()`. It has a check for circular dependencies, and this gets triggered multiple times while processing Gst-1.0 (gstreamer). AFAICT this is because gstreamer has its own Object type (`Gst.Object`) which depends on `GObject.InitiallyUnowned` which depends in turn on `GObject.Object`. So there are two "Object"s in the same tree which are actually different classes. I think this can be fixed reasonably easily by comparing qualified names. For `girClass` we can use `_fullSymName`, and I think we can reliably assume `parentPtr` will have a `_module` field.

BTW, I've been working on rebasing my fork off yours, adding the command line `--inheritance`. I believe they're ready to merge apart from this issue (and any other issues I might find in the Gst-1.0 output once this is fixed).

**Comment by JumpLink** [comment]
@realh thank you very much! I will check this in a few days
