### ISSUE TITLE
npm install got errors

### ISSUE THREAD

**Issue by kerojiang** [sammydre/ts-for-gjs#35]
when I typyed the npm install 
I got this errors:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ts-for-gir@1.0.1 validate:gjs: `tsc --noEmit ./@types/Gjs/*.ts`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ts-for-gir@1.0.1 validate:gjs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

my nodejs version is v15.3.0
how should I do?

**Comment by JumpLink** [comment]
The repository has changed a lot since this issue, so I assume that this issue will no longer fit the current code
