### ISSUE TITLE
[node-gtk] Typing breaks for multi-value return

### ISSUE THREAD

**Issue by peat-psuwit** [sammydre/ts-for-gjs#46]
According to #21 point 6, not every function with multiple return values are overridden to return object instead of array. For example, currently GstSdp 1.0 has this type in the typing:

```ts
export function sdpMediaNew(): { returnType: SDPResult, media: SDPMedia }
```

However, this function is not overridden within node-gtk:

```
$ node
Welcome to Node.js v16.13.2.
Type ".help" for more information.
> const gi = require('node-gtk')
undefined
> const Gst = gi.require('Gst', '1.0')
undefined
> Gst.init()
[]
> const GstSdp = gi.require('GstSdp', '1.0')
undefined
> GstSdp.sdpMediaNew()
[ 0, SDPMedia {} ]
> 
```

From bisect, this is introduced by by commit 30670c7d ("[node-gtk] Fix return type overwrites, see #21 point 6").

**Comment by peat-psuwit** [comment]
// cc @JumpLink

**Comment by JumpLink** [comment]
@peat-psuwit thank you to find this out. The question is, how do we know that the return value has been overwritten or not?  Can we automate this or do we have to keep a list by hand?

**Comment by peat-psuwit** [comment]
node-gtk has all overrides implemented in JS, located at [lib/overrides](https://github.com/romgrk/node-gtk/blob/master/lib/overrides). According to #21 point 6, those that have different returns will contain JSDoc annotation. So, I guess one can use some JSDoc parser to parse that out and do some automation on it.

I'm not sure how to integrate that into ts-for-gir though...

**Comment by JumpLink** [comment]
I think that would be too much overhead. There are not many methods and they do not change often. Therefore, I think we can maintain a list here by hand. I can do that if you don't have time for it

**Comment by peat-psuwit** [comment]
Please do.

**Comment by JumpLink** [comment]
@peat-psuwit Should be fixed now in my branch / PR. Adding overrides is now very easy, see [src/type-patches.ts#L98](https://github.com/gjsify/ts-for-gjs/blob/main/src/type-patches.ts#L98)
