### ISSUE TITLE
No mapping for 'filename' type

### ISSUE THREAD

**Issue by realh** [sammydre/ts-for-gjs#5]
When running the tool I noticed lots of warning messages like:
`Could not find type Gio.filename for commandline`
I think this is because you haven't provided a mapping for gir's `filename` type which is a `char *` that isn't necessarily UTF-8. Is that a deliberate decision to treat such strings make sure that gjs doesn't trip up by trying to decode non-unicode strings? If so it would be a good idea to add `'filename': 'any'` to `podTypeMap` to get rid of the annoying messages. Or would it be better to treat non-unicode filenames as an obscure and deprecated corner case, and map them to strings?

**Comment by sammydre** [comment]
No reason I don't think -- it's just not implemented yet.

`string` seems like a good choice to me. Happy to see pull requests!
