### ISSUE TITLE
missing lib folder

### ISSUE THREAD

**Issue by aggalex** [sammydre/ts-for-gjs#50]
`sh: line 1: ../../../lib/start.js: No such file or directory`

Seems like something's missing...

**Comment by JumpLink** [comment]
@aggalex Did you follow the install instructions?

```bash
git clone https://github.com/sammydre/ts-for-gjs
cd ts-for-gjs
git submodule update --init
npm install
npm link
```

Sorry here is still missing a command:

```bash
git clone https://github.com/sammydre/ts-for-gjs
cd ts-for-gjs
git submodule update --init
npm install
npm run build # <- missing
npm link
```

You can also use `ts-for-gir` without building it first by running the following in the root of the repository:

```bash
npm run start -- generate --configName='.ts-for-gir.regress.rc.js'
```

**Comment by JumpLink** [comment]
@aggalex let me know if it works now

**Comment by aggalex** [comment]
oh yes thanks. Didn't notice that one
